### ISSUE TITLE
correction for noto sans deseret needed

### ISSUE THREAD

**Issue by GoogleCodeExporter** [notofonts/deseret#1]
```
What steps will reproduce the problem?
1.Enter glyphs for Deseret Capital and Small Letter Vees
2.NOTE: the glyphs are in Unicode U+1041A
3.

What is the expected output? What do you see instead?
Carefully described in the attachment

What version of the product are you using? On what operating system?
Noto Sans Deseret font -- on Windows 7, Microsoft Word (using proper Unicode 
locations

Please provide any additional information below.
Noted in attachment -- please examine

```

Original issue reported on code.google.com by `prmach...@gmail.com` on 4 May 2015 at 9:40

Attachments:
- [noto-sans-deseret-corrections.pdf](https://storage.googleapis.com/google-code-attachments/noto/issue-359/comment-0/noto-sans-deseret-corrections.pdf)

**Comment by GoogleCodeExporter** [comment]
```
Forgot to enter Unicode designation Deseret Small Letter Vee U+10442, but it is 
included in attachment
```

Original comment by `prmach...@gmail.com` on 4 May 2015 at 9:41

**Comment by GoogleCodeExporter** [comment]
```
Confirming the bug. Assigning to Monotype to fix.
```

Original comment by `roozbeh@google.com` on 4 May 2015 at 11:35
- Changed state: **Accepted**

**Comment by behdad** [comment]
cc @roozbehp

**Comment by nizarsq** [comment]
Not sure what is the original bug is, I created test case for 1041A 10442 and they look different from unicode standard https://unicode.org/charts/PDF/U10400.pdf  and other third party fonts.
<img width="1232" alt="Screen Shot 2020-08-01 at 6 00 01 PM" src="https://user-images.githubusercontent.com/22158882/89113073-d40ec080-d420-11ea-9b0b-08e1aabe0247.png">

**Comment by SKing-2003** [comment]
Closing in favour of #2
